GET http://localhost:5000
```
###
GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJKb2huIFNpbnMiLCJlbWFpbCI6ImpvaG5zaW5zQGdtYWlsLmNvbSIsImlhdCI6MTcwMDE1NjE4MywiZXhwIjoxNzAwMTU2MjEzfQ.lOzxBVxg-YKTsvIPmU8WU7dIC0uNsUpcm3dfEdDRZ4U

###
GET http://localhost:5000/users/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJKb2huIFNpbnMiLCJlbWFpbCI6ImpvaG5zaW5zQGdtYWlsLmNvbSIsImlhdCI6MTcwMDE1NjE4MywiZXhwIjoxNzAwMTU2MjEzfQ.lOzxBVxg-YKTsvIPmU8WU7dIC0uNsUpcm3dfEdDRZ4U
###
POST http://localhost:5000/register
Content-Type: application/json

{
    "name": "John Doe",
    "email": "johndoe@gmail.com",
    "password": "password",
    "confirm_password": "password"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "johnsins@gmail.com",
    "password": "password"
}

###
GET http://localhost:5000/token

###
DELETE http://localhost:5000/logout

### Nutrisions!
GET http://localhost:5000/nutrisions


###
POST http://localhost:5000/nutrisions
Content-Type: application/json

{
    "name" : "Mango",
    "description" : "Mango is rich in vitamins, minerals, and antioxidants, and it has been associated with many health benefits, including potential anticancer effects, as well as improved immunity and digestive and eye health"
}

### Meals!
POST http://localhost:5000/meals
Content-Type: application/json

{
    "userId": "1"
}

###
POST http://localhost:5000/addmeal
Content-Type: application/json

{
    "meals_name" : "Gado - Gado",
    "userId": 1,
    "calories": "200"
}

### Random Facts!
GET http://localhost:5000/facthealths

###


POST http://localhost:5000/facthealths
Content-Type: application/json

{
    "fact": "Regular Health Check-ups are Essential: Regular medical check-ups and screenings can help detect potential health issues early, allowing for timely intervention and prevention.",
    "source": "https://www.heart.org/en/health-topics/consumer-healthcare/doctor-appointments-questions-to-ask-your-doctor"
}